### ISSUE TITLE
Live migration of a simple app from machine A to machine B with go-criu

### ISSUE THREAD

**Issue by bvqbao** [checkpoint-restore/go-criu#13]
Hello,

Is there any examples showing how to do a live migration of a simple app from machine A to machine B with go-criu?

The example given in the go-criu repository (phaul-main.go) only shows a very simplistic scenario where the machine A  (source) = the machine B (destination).

If the source machine and the destination machine are two separate machines, what is the setup needed in order to realize a simple live migration?

I have looked into the code and here is my understanding:

- Need to setup a shared storage between the two machines for storing image files (to avoid moving/copying the image files).
- Create 2 go programs that will be executed on the two machines (currently in the phaul-main.go example, these two programs are mixed up togother)
	+ A phaul client (MakePhaulClient) running on machine A and a phaul server (MakePhaulServer) running on machine B.
	+ Use TCP/IP socket instead of unix socket (AF_LOCAL) to setup memfd
	+ What I don't understand is that in the phaul-main.go example, the server handler is passed to MakePhaulClient as an argument. How can we do that if there are now two different programs?

Thanks,
Bao.

**Comment by adrianreber** [comment]
> Is there any examples showing how to do a live migration of a simple app from machine A to machine B with go-criu?

Unfortunately that is not what go-criu is designed for. This are only the Go bindings to be used in other projects. phaul (Go) is not really used anywhere and we just moved it here because this is the place of our Go code.

You should only use this repository if you need want to include the Go CRIU bindings in your project.

**Comment by bvqbao** [comment]
My bad. I mean with phaul, not go-criu. But I guess at the current state, we cannot do live migration with phaul yet, right?

**Comment by adrianreber** [comment]
> But I guess at the current state, we cannot do live migration with phaul (go) yet, right?

No phaul (Go) is a simple reference implementation how it could look like, but if you want to use it you need to adapt it to your needs.

Podman, Docker, LXC/LXD offer implementations to do container live migration. You can use one of those and work with the existing communities to improve it.
