### ISSUE TITLE
CRIT: use proto names instead of camelCase in JSON

### ISSUE THREAD

**Issue by snprajwal** [checkpoint-restore/go-criu#154]
Currently, the CRIT package serialises protobuf to JSON with camelCase for the field names. This was chosen as a design decision to prevent having to annotate every protobuf field manually with the actual snake_case name in the marshaling/unmarshaling logic. Incidentally, I discovered that the `protojson` package now allows configuring this particular case via `protojson.MarshalOptions` ([`UseProtoNames`](https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson#MarshalOptions)). Enabling this will reduce the parity between the Go and Python CRIT libraries, since the Python library uses the snake_case names from the proto definitions for the fields. Is this something we should enable? While it will not break API, it will definitely break the JSON output compared to before, and if anyone is using custom logic to parse the JSON (although the shouldn't), it will cause their package to break.

cc @rst0git @adrianreber

**Comment by snprajwal** [comment]
ping @rst0git

**Comment by rst0git** [comment]
@snprajwal If I understand correctly, the output from the Go version of CRIT currently uses camelCase for *keys* while the Python version uses snake_case (as illustrated below).

Go:
```JSON
{
    "magic": "INVENTORY",
    "entries": [
        {
            "imgVersion": 2,
            "fdinfoPerId": true,
            "rootIds": {
                "vmId": 1,
                "filesId": 1,
                "fsId": 1,
                "sighandId": 1,
                "pidNsId": 1,
                "netNsId": 2,
                "ipcNsId": 3,
                "utsNsId": 4,
                "mntNsId": 6,
                "userNsId": 7,
                "cgroupNsId": 8,
                "timeNsId": 5
            },
            "nsPerId": true,
            "rootCgSet": 1,
            "lsmtype": "SELINUX",
            "networkLockMethod": 0
        }
    ]
}

```

Python:
```json
{
    "magic": "INVENTORY",
    "entries": [
        {
            "img_version": 2,
            "fdinfo_per_id": true,
            "root_ids": {
                "vm_id": 1,
                "files_id": 1,
                "fs_id": 1,
                "sighand_id": 1,
                "pid_ns_id": 1,
                "net_ns_id": 2,
                "ipc_ns_id": 3,
                "uts_ns_id": 4,
                "mnt_ns_id": 6,
                "user_ns_id": 7,
                "cgroup_ns_id": 8,
                "time_ns_id": 5
            },
            "ns_per_id": true,
            "root_cg_set": 1,
            "lsmtype": "SELINUX",
            "network_lock_method": 0
        }
    ]
}
```


>  Is this something we should enable? 

It would be good if we can use the same output format with both versions of CRIT.

@adrianreber What do you think?

**Comment by snprajwal** [comment]
@adrianreber ping

**Comment by adrianreber** [comment]
Having the same output as Python sounds like the right idea. Not sure how many people depend on the CamelCase. Can you make it configurable during runtime?

**Comment by snprajwal** [comment]
Yes that can be done quite trivially

**Comment by snprajwal** [comment]
IMHO, I think we should be sticking to just the snake_case names since it's consistent with the Python version. Also, if someone is dependent on the camel-casing of the JSON output, that would mean they're using custom struct definitions instead of the ones generated from the protobuf definitions in the CRIU tree, which should be discouraged in the first place.

**Comment by adrianreber** [comment]
Sounds good.
