### ISSUE TITLE
Make 7.1.0 release

### ISSUE THREAD

**Issue by adrianreber** [checkpoint-restore/go-criu#167]
@snprajwal Do you think you have time to create a 7.1.0 release?

**Comment by rst0git** [comment]
Could we also include https://github.com/checkpoint-restore/go-criu/pull/163 in this release?

**Comment by adrianreber** [comment]
The main reason I want to have a release is to do changes in CRI-O related to #165

#163 is still draft, so not sure. We can always make one more release once that is merged.

**Comment by snprajwal** [comment]
Fair enough, we can reserve #163 for v7.2.0

**Comment by snprajwal** [comment]
@adrianreber the release has been made :)

**Comment by adrianreber** [comment]
Thank you!
