### ISSUE TITLE
mempages_test & stats_test test failed for v7.1.0

### ISSUE THREAD

**Issue by Riteshkr22** [checkpoint-restore/go-criu#174]
I am doing test build which is falling How to solve ?
`go test ./...`
But getting failed some tests related to mempages_test & stats_test like this 
$ go test ./...
?       github.com/checkpoint-restore/go-criu/v7        [no test files]
--- FAIL: TestNewMemoryReader (0.00s)
    mempages_test.go:20: error opening binary file: open test-imgs/pstree.img: no such file or directory
--- FAIL: TestGetMemPages (0.00s)
    mempages_test.go:85: error opening binary file: open test-imgs/pstree.img: no such file or directory
--- FAIL: TestGetPsArgsAndEnvVars (0.00s)
    mempages_test.go:194: error opening binary file: open test-imgs/pstree.img: no such file or directory
--- FAIL: TestGetShmemSize (0.00s)
    mempages_test.go:254: error opening binary file: open test-imgs/pstree.img: no such file or directory
--- FAIL: TestGetDumpStats (0.00s)
    stats_test.go:8: Failed to get stats
    stats_test.go:11: PagesWritten is 0
--- FAIL: TestGetRestoreStats (0.00s)
    stats_test.go:18: Failed to get stats
    stats_test.go:21: ForkingTime is 0
FAIL
FAIL    github.com/checkpoint-restore/go-criu/v7/crit   0.003s
?       github.com/checkpoint-restore/go-criu/v7/crit/cli       [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/cmd       [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/apparmor   [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/autofs     [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/binfmt-misc        [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/bpfmap-data        [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/bpfmap-file        [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/cgroup     [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/core-aarch64       [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/core-arm   [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/core-mips  [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/core-ppc64 [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/core-s390  [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/core-x86   [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/cpuinfo    [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/creds      [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/criu-core  [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/criu-sa    [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/eventfd    [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/eventpoll  [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/ext-file   [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/fdinfo     [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/fh [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/fifo       [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/file-lock  [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/fown       [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/fs [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/fsnotify   [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/ghost-file [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/img-streamer       [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/inventory  [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/ipc-desc   [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/ipc-msg    [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/ipc-sem    [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/ipc-shm    [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/ipc-var    [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/macvlan    [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/memfd      [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/mm [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/mnt        [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/netdev     [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/ns [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/opts       [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/packet-sock        [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/pagemap    [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/pidns      [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/pipe       [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/pipe-data  [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/pstree     [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/regfile    [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/remap-file-path    [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/rlimit     [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/rseq       [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/seccomp    [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/siginfo    [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/signalfd   [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/sit        [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/sk-inet    [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/sk-netlink [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/sk-opts    [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/sk-packet  [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/sk-unix    [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/stats      [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/sysctl     [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/tcp-stream [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/time       [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/timens     [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/timer      [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/timerfd    [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/tty        [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/tun        [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/userns     [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/utsns      [no test files]
?       github.com/checkpoint-restore/go-criu/v7/crit/images/vma        [no test files]
?       github.com/checkpoint-restore/go-criu/v7/magic  [no test files]
?       github.com/checkpoint-restore/go-criu/v7/phaul  [no test files]
?       github.com/checkpoint-restore/go-criu/v7/rpc    [no test files]
ok      github.com/checkpoint-restore/go-criu/v7/scripts/magic-gen      0.002s
?       github.com/checkpoint-restore/go-criu/v7/stats  [no test files]
?       github.com/checkpoint-restore/go-criu/v7/test   [no test files]
?       github.com/checkpoint-restore/go-criu/v7/test/crit      [no test files]
?       github.com/checkpoint-restore/go-criu/v7/test/phaul     [no test files]
?       github.com/checkpoint-restore/go-criu/v7/utils  [no test files]
FAIL

Please explain why this has failed and also let me know if this test is important or not.

**Comment by adrianreber** [comment]
Take a look how we run the tests in CI: https://github.com/checkpoint-restore/go-criu/blob/master/.github/workflows/main.yml

Basically you need to go through the makefile and not call `go test` directly.

**Comment by snprajwal** [comment]
As Adrian mentioned, the tests require checkpoint files that are generated by another Makefile target. You would need to invoke `sudo make test` to be able to run them successfully.
