### ISSUE TITLE
readme: Contributor guidelines

### ISSUE THREAD

**Issue by rst0git** [checkpoint-restore/go-criu#2]
We need to describe how do contributors submit patches for `go-criu`?

GitHub pull requests, mailing list, both?

**Comment by adrianreber** [comment]
I am not sure how to handle the `go-criu` repository. On the one hand I agree with @xemul that everything is already documented and if everything goes through the mailing list the patches have the same community exposure and review, but on the other hand I also think we could work with pull requests for `go-criu` as that feels closer to how I would expect a Go project to operate.

For `go-criu` both approaches seem doable, but we should definitely document it.

**Comment by xemul** [comment]
@adrianreber , I wouldn't mix two approaches together within single repo. So if for go-criu the PR fits better, then it's better not to have ML discussions on it.

**Comment by adrianreber** [comment]
@xemul, right, mixing would be a bad idea. I would prefer pull requests.

@avagin, what do you say, would pull request be a bad idea from your point of view?

**Comment by avagin** [comment]
> @avagin, what do you say, would pull request be a bad idea from your point of view?

I'm ok to work with pull requests. Especially in a case if you would agree to be a maintainer if this project.

**Comment by adrianreber** [comment]
Alright, I can be maintainer of `go-criu`, especially as I will be using it most, at least for the next time. In the beginning I would try to use it from Podman and extend it when needed. My goal would be to also make use in `runc` of these CRIU bindings to reduce code duplication. Let's see if this will happen...

@rst0git can you add a section to the README.md about pull requests?

**Comment by adrianreber** [comment]
Thanks everyone for the input.
