### ISSUE TITLE
Tag SemVer-compatible tags to facilitate go modules

### ISSUE THREAD

**Issue by thaJeztah** [checkpoint-restore/go-criu#20]
I'm not sure if go-criu is following SemVer semantics, but if so, it would be great to tag the current (v3.11) release as `v3.11.0`, so that Go modules can refer to the tag (instead of by commit).

/cc @kolyshkin

**Comment by adrianreber** [comment]
go-criu is not following semver. go-criu is following CRIU. The latest and only release is tagged with v3.11. Now that CRIU 3.14 is released I am planing to do a new go-criu release.

Is the v3.11 tag not enough for Go modules? Does it need to be v3.11.0? Which would not be a real problem.

**Comment by thaJeztah** [comment]
Yes, it's a bit of a pain wrt go modules, and not sure what's the best approach; adding a `.0` would make Go modules accept the tags, but at the same time it's "cheating the system" if you're not following SemVer rules (so users may update to v3.13.0 or v3.14.0, and expect it to be fully compatible (being a "minor" release)).

From that perspective, _not_ having tags that Go would regard as SemVer would be better.

**Comment by adrianreber** [comment]
We decided to follow SemVer starting with the upcoming 4.0.0 release which will track CRIU 3.14.

I created a runc PR (https://github.com/opencontainers/runc/pull/2409) to use the latest version which I have to update once I have tagged go-criu.

**Comment by thaJeztah** [comment]
Thanks for the update! One possible concern (for your maintenance) might be that Go modules "expects" import paths to match the major version (so the import path would be `github.com/checkpoint-restore/go-criu/v4/...`), and their recommendation is to actually put the code in a _directory_ named `vX` (which is, well, don't get me started).

I think there's a couple of options there;

1. ignore their recommendation; things will work, but projects using go modules will see a `+incompatible` commentafter the version in their `go.mod`. The _intent_ is that multiple dependencies in your project could use different _major_ versions of a module (e.g. one dependency uses `criu v4.xx`, and another `criu v5.xx`). Not sure if this would be a "thing" in practice.
2. given that all tags so far haven't been "SemVer", from a "go modules" perspective, this project has not yet done a release. This gives you some ("creative") flexibility; if you're not sure if the Go API is "stable", you could tag the releases as "pre-1.0" versions. This is the approach kubernetes took (e.g. `k8s.io/cri-api v0.18.2` corresponds with `kubernetes v1.18.2`). Pre-1.0 releases don't require a change to the import path on breaking changes (as they're pre-1.0, so implicitly "unstable").

Just thought I'd mention some options, before any "definitive" changes are made.

**Comment by thaJeztah** [comment]
oh, and just then I realised v4.0.0 was tagged, so ignore my previous comment 😅 😂

**Comment by adrianreber** [comment]
Currently I really hate modules :wink:  It feels complicated and I have no idea what I am doing.

I tagged it and I have a go.mod file in go-criu, but running make vendor on runc complains about missing something about `latest`.

If you have any recommendations how to do it correctly I am more than happy to follow any ideas you have.

**Comment by thaJeztah** [comment]
> Currently I really hate modules 😉 It feels complicated and I have no idea what I am doing.

Welcome to the club! (😞)

@samwhited @kolyshkin I think you both played more with this stuff; could you help out?

**Comment by SamWhited** [comment]
> Currently I really hate modules wink It feels complicated and I have no idea what I am doing.

I'd urge you to take your concerns to the go-nuts mailing list or the issue tracker if you're running into actual problems with how modules interacts with this project. So far whenever I've brought up concerns, including issues with real projects, I've been told that these are a small percentage of users and modules solves 90% of use cases, etc. I do not believe this is the case, but unless they get more complaints the Go team are likely to continue asserting that everything is fine.

That being said, the only problem I see is that this module declares itself as `/v4` (which is correct) but then imports `github.com/checkpoint-restore/go-criu`, so it will actually be importing an older version of itself.

The `go.mod` file appears to be out of date as well, and the `go.sum` file doesn't seem to exist (but this should be committed).

**Comment by adrianreber** [comment]
@SamWhited thanks a lot, adding v4 everywhere actual makes it build again.

**Comment by adrianreber** [comment]
Thanks everyone for helping us out here! It seems to work now.

**Comment by thaJeztah** [comment]
Thanks!
