### ISSUE TITLE
Unable to restore TCP_CORK (1): Operation not supported

### ISSUE THREAD

**Issue by jaydom** [checkpoint-restore/go-criu#31]
root@test:/home/admin/go-criu/test# rm -rf image/ && go run phaul-main.go 16956
Make server part (socket 4)
Make client part (socket 3)
Migrate
S: start iter
`- grow iter (163) reached
S: start iter
Final stage
Do dump
Failed: operation failed (msg:Error (criu/util.c:981): Unable to restore TCP_CORK (1): Operation not supported
 err:0)
exit status 1

**Comment by rst0git** [comment]
A similar issue has been reported in https://github.com/checkpoint-restore/criu/issues/549
