### ISSUE TITLE
Proposal: implement stricter merge rules

### ISSUE THREAD

**Issue by kolyshkin** [checkpoint-restore/go-criu#48]
I think we should have stricter merge rules.

Currently:
 - some PRs are merged with merge commit, some without;
 - some PRs are merged by its author without any reviews/LGTMs.

I propose:
1. Require at least one LGTM (both being not from the author) to be able to merge PRs. I would say 2 LGTMs but there are not enough maintainers here.
2. Require merge commits from PR (i.e. disable "rebase and merge" and "squash and merge" options). This is important as github PRs often contains additional information and discussions about the commits. Without a merge PR, it is much harder to track a commit back to the PR it originated from, and thus find that additional information;
3. Require CI jobs to be green in order to merge (just as a precaution mechanism).

If everyone from @checkpoint-restore/go-criu-maintainers agrees, I'll implement the changes. Please vote in comments.

 - [x] @adrianreber 
 - [x] @avagin
 - [x] @kolyshkin 
 - [x] @rst0git

**Comment by avagin** [comment]
LGTM

**Comment by rst0git** [comment]
> Require merge commits from PR (i.e. disable "rebase and merge" and "squash and merge" options). This is important as github PRs often contains additional information and discussions about the commits. Without a merge PR, it is much harder to track a commit back to the PR it originated from, and thus find that additional information;

I agree that PRs contain additional information and discussions that are important, but why is it harder track a commit back to the PR?
<img width="1673" alt="Screen Shot 2021-02-19 at 6 51 00 AM" src="https://user-images.githubusercontent.com/9142901/108468784-27dadd00-727f-11eb-9f44-7e3e10712a48.png">

In general, I prefer "rebase and merge" because it makes it easier to use `git log` and other git commands.

<img width="1399" alt="Screen Shot 2021-02-19 at 6 54 39 AM" src="https://user-images.githubusercontent.com/9142901/108469007-75574a00-727f-11eb-8b41-fc2030f2445f.png">

**Comment by adrianreber** [comment]
Yes, I could never really decide which approach I like better. Both ways of merging have pros and cons. I like that there are rules now and they sound good to me. LGTM.

**Comment by kolyshkin** [comment]
> why is it harder track a commit back to the PR?

I am using git cli to do that, here's a part of my `~/.gitconfig`:
```
[alias]
	find-merge = "!sh -c 'commit=$0 && branch=${1:-HEAD} && (git rev-list $commit..$branch --ancestry-path | cat -n; git rev-list $commit..$branch --first-parent | cat -n) | sort -k2 -s | uniq -f1 -d | sort -n | tail -1 | cut -f2'"
	show-merge = "!sh -c 'merge=$(git find-merge $0 $1) && [ -n \"$merge\" ] && git show $merge'"
```

and I use it like this:

```console
[kir@kir-rhat go-criu]$ git show-merge d7c0d9c4e8cd4b506aa9d1b8b4d143a7e46cb512
commit 483ea8861d1e7e0835cb083e77878ccef99cd4ee
Merge: d028d97 d7c0d9c
Author: Adrian Reber <adrian@lisas.de>
Date:   Thu Feb 11 07:40:12 2021 +0100

    Merge pull request #43 from kolyshkin/proto-up
    
    Update protobuf files and go mod/sum

```

I understand I can just go to github.com, open a commit and there will be a link to PR, but for some reason this is how I do things. I also think that maybe github cli tool is a better option.

But in any case, we just need to decide on one way or another, and it seems most projects use merge commits. It does not matter much, I'm probably OK without merge commits, we just need to decide.

**Comment by rst0git** [comment]
Considering the pros and cons of both methods, I think using the default merge option for PRs in GitHub might be better.

The following is a brief comparison based on the [GitHub Docs](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges).

---

#### Merge

##### Advantages
- Default in GitHub and many projects use it.
- Can automatically merge pull requests on GitHub even if there are merge conflicts.

##### Disadvantages:
- Creates a "merge commit" for every PR that can make it hard for other developers to understand the history of the project.

---

#### Rebase and merge

##### Advantages
- Cleaner linear project history without unnecessary merge commits.

##### Disadvantages
- Contributors may have to rebase on the command line, resolve any conflicts, and force push their changes to the pull request's branch before the "rebase and merge"  option can be used on GitHub.

**Comment by kolyshkin** [comment]
OK, I'll go ahead and implement the changes.

**Comment by kolyshkin** [comment]
Done. Please let me know if anything is wrong or broken.

**Comment by rst0git** [comment]
Thanks!

**Comment by adrianreber** [comment]
Closing this as you say it is implemented.

**Comment by adrianreber** [comment]
@kolyshkin Your latest PR (#49) seems to use auto merge but looking at the settings of the repository I do not see auto merge enabled.

Also, it does not auto merge because some commits are not signed. I actually like signed commits and do gpg sign my commits, but I do not know where this can be configured as a requirement.

**Comment by adrianreber** [comment]
I found the requirements for signed commits. I like it, but we do not have to enforce it.

**Comment by kolyshkin** [comment]
> Your latest PR (#49) seems to use auto merge but looking at the settings of the repository I do not see auto merge enabled.

I think what happened is I had it enabled for some time, and then I disabled it back. I think it does not make sense to have it unless CI takes hours, which is not the case for this repo. The idea for automerge is once there are enough LGTMs (1 for this repo) and CI succeds, the commit is merged. Here, I think, it's OK to merge manually as CI does not take long.

> Also, it does not auto merge because some commits are not signed. I actually like signed commits and do gpg sign my commits

AFAIK in here by signed commits they do not mean gpg-signed, but merely DCO (i.e. `Signed-off-by: `). I think we should require signed-off-by.

**Comment by kolyshkin** [comment]
Nope, I was wrong, this option is actually requiring gpg-signed commits.

**Comment by kolyshkin** [comment]
I went ahead and disabled the requirement for gpg signed commits.
