### ISSUE TITLE
create a release?

### ISSUE THREAD

**Issue by vrothberg** [checkpoint-restore/go-criu#5]
I am currently going through Podman's dependencies (updating the vendor.conf) trying to pin them to releases when possible and available. Some distribution, Debian in particular, are very conservative regarding go packaging as many libraries don't have any release (or no semantic versioning).

Would you consider creating releases of go-criu?

**Comment by rst0git** [comment]
cc: @adrianreber

**Comment by adrianreber** [comment]
> Would you consider creating releases of go-criu?

Sure, no problem.

@rst0git, my first idea was to just use the same version number as CRIU. What do you think?

**Comment by rst0git** [comment]
> @rst0git, my first idea was to just use the same version number as CRIU. What do you think?

Make sense (and it seems like a good practice), especially since the bindings will correspond to a specific CRIU version.

**Comment by adrianreber** [comment]
@vrothberg I created a v3.11 tag and github created a release for us. Does that help you?

@rst0git we should probably document that we will be following CRIU version numbers.

**Comment by vrothberg** [comment]
> @vrothberg I created a v3.11 tag and github created a release for us. Does that help you?

That's awesome. Thanks a lot for the quick response!

> @rst0git we should probably document that we will be following CRIU version numbers.

I think this would help packagers a lot.
