### ISSUE TITLE
undefined: syscall.Socketpair and undefined: syscall.AF_LOCAL

### ISSUE THREAD

**Issue by dongliangde** [checkpoint-restore/go-criu#50]
My current development environment go 1.16
package main

import (
	"github.com/checkpoint-restore/go-criu/v5"
	"log"
)

func main() {
	c := criu.MakeCriu()
	version, err := c.GetCriuVersion()
	if err != nil {
		log.Fatalln(err)
	}
	log.Println(version)
}

The following error occurs
# github.com/checkpoint-restore/go-criu/v5
github.com\checkpoint-restore\go-criu\v5@v5.0.0\main.go:37:14: undefined: syscall.Socketpair
github.com\checkpoint-restore\go-criu\v5@v5.0.0\main.go:37:33: undefined: syscall.AF_LOCAL

**Comment by dongliangde** [comment]
Running depends on the go version？

**Comment by adrianreber** [comment]
Are you running on Linux?

**Comment by dongliangde** [comment]
> 您在Linux上运行吗？



> Are you running on Linux?

**Comment by dongliangde** [comment]
> Are you running on Linux?

I run it on windows

**Comment by adrianreber** [comment]
> > Are you running on Linux?
> 
> I run it on windows

CRIU is Linux only.

**Comment by dongliangde** [comment]
> > > 您在Linux上运行吗？
> > 
> > 
> > 我在Windows上运行
> 
> CRIU仅是Linux。

thank you
