### ISSUE TITLE
tty: Don't have tty to inherit session from, aborting  err:0

### ISSUE THREAD

**Issue by dongliangde** [checkpoint-restore/go-criu#51]
There will be an error when resuming the frozen program
Here are the mistakes
(criu/tty.c:1014): tty: Don't have tty to inherit session from, aborting
 err:0

**Comment by dongliangde** [comment]
resolved

**Comment by lichangyu2022** [comment]
How did you solve this problem? I also encountered this problem

**Comment by Jeffwan** [comment]
@dongliangde Can you share how you resolve the issue?
