### ISSUE TITLE
go-criu and runc cause runtime errors

### ISSUE THREAD

**Issue by vrothberg** [checkpoint-restore/go-criu#7]
go-criu and runc are causing issues at runtime. I noticed it while updating dependencies over at CRI-O (https://github.com/kubernetes-sigs/cri-o/pull/2124). go-criu is pulled in via libpod.

Is this a known issue? Do you know how we could workaround that?
```
[valentin@nebuchadnezzar cri-o]$ ./bin/crio
2019/03/12 15:02:37 proto: duplicate proto type registered: criu_page_server_info
2019/03/12 15:02:37 proto: duplicate proto type registered: criu_veth_pair
2019/03/12 15:02:37 proto: duplicate proto type registered: ext_mount_map
2019/03/12 15:02:37 proto: duplicate proto type registered: join_namespace
2019/03/12 15:02:37 proto: duplicate proto type registered: inherit_fd
2019/03/12 15:02:37 proto: duplicate proto type registered: cgroup_root
2019/03/12 15:02:37 proto: duplicate proto type registered: unix_sk
2019/03/12 15:02:37 proto: duplicate proto type registered: criu_opts
2019/03/12 15:02:37 proto: duplicate proto type registered: criu_dump_resp
2019/03/12 15:02:37 proto: duplicate proto type registered: criu_restore_resp
2019/03/12 15:02:37 proto: duplicate proto type registered: criu_notify
2019/03/12 15:02:37 proto: duplicate proto type registered: criu_features
2019/03/12 15:02:37 proto: duplicate proto type registered: criu_req
2019/03/12 15:02:37 proto: duplicate proto type registered: criu_resp
2019/03/12 15:02:37 proto: duplicate proto type registered: criu_version
panic: proto: duplicate enum registered: CriuCgMode

goroutine 1 [running]:
github.com/kubernetes-sigs/cri-o/vendor/github.com/golang/protobuf/proto.RegisterEnum(...)
        /home/valentin/go/src/github.com/kubernetes-sigs/cri-o/vendor/github.com/golang/protobuf/
proto/properties.go:458
github.com/kubernetes-sigs/cri-o/vendor/github.com/opencontainers/runc/libcontainer/criurpc.init.
0()
        /home/valentin/go/src/github.com/kubernetes-sigs/cri-o/vendor/github.com/opencontainers/r
unc/libcontainer/criurpc/criurpc.pb.go:1058 +0x549
```

**Comment by adrianreber** [comment]
go-criu is pulled in via libpod and the same definitions are also part of runc. The runc version in cri-o seems to be still the old version from before runc was also using go-criu.

Not totally sure how this works in Go when multiple vendored-in projects already vendor-in the same Go code. One recommendation would be to vendor-in a newer runc into cri-o to have the same CRIU RPC definitions from go-criu in runc and libpod.

**Comment by adrianreber** [comment]
I see that you already opened a PR to update runc in cri-o. But as the latest runc version from November 2018 it does not contain the vendored-in go-criu.

**Comment by vrothberg** [comment]
> I see that you already opened a PR to update runc in cri-o. But as the latest runc version from November 2018 it does not contain the vendored-in go-criu.

Thanks a lot, @adrianreber! In my desperation, I did not check the latest master of runc which I just vendored into CRI-O that is finally happy.
