### ISSUE TITLE
Please add copyright statement

### ISSUE THREAD

**Issue by onlyjob** [checkpoint-restore/go-criu#8]
Copyright statement appears to be missing...

**Comment by adrianreber** [comment]
The README file states the license. There is also a LICENSE file in the repository. Anything else you are looking for?

**Comment by onlyjob** [comment]
[Copyright statement](https://github.com/checkpoint-restore/go-criu/blob/master/LICENSE#L189) is [required by the LICENSE](https://github.com/checkpoint-restore/go-criu/blob/master/LICENSE#L178).

Grant of license is not the same as copyright statement...

**Comment by adrianreber** [comment]
Do I have to change the LICENSE file?

**Comment by onlyjob** [comment]
You can but text of the license recommends to include a [header](https://github.com/checkpoint-restore/go-criu/blob/master/LICENSE#L189-L201) to all the files (there are only about 10 of them). I would include it to README as well to avoid any doubts. Thanks.

**Comment by adrianreber** [comment]
Should be fixed by #10
