### ISSUE TITLE
v6.0.0 release

### ISSUE THREAD

**Issue by snprajwal** [checkpoint-restore/go-criu#86]
## New features
- `crit` library
## Breaking changes
- Deprecate `stats` and `rpc` in favour of `crit`
## Related projects that will need PRs
- [x] [runc](https://github.com/opencontainers/runc/)
- [x] [checkpointctl](https://github.com/checkpoint-restore/checkpointctl)
- [x] [podman](https://github.com/containers/podman)
- [x] [LXD](https://github.com/lxc/lxd)

**Comment by rst0git** [comment]
Prajwal and I discussed if we could deprecate the "stats" functionality of go-criu in favor of the [crit package](https://github.com/checkpoint-restore/go-criu/tree/master/crit).

This functionality is currently used for `--print-stats` in checkpointctl (https://github.com/checkpoint-restore/checkpointctl/pull/12) and Podman (https://github.com/containers/podman/pull/12184). However, to be able to update checkpointctl / Podman we might need to first create a new release of go-criu that includes the crit package.

In addition, somewhat similar functionality was introduced in LXD sometime ago that is parsing the `stats-dump` file to enable pre-copy migration (https://github.com/lxc/lxd/pull/4072). If we could integrate go-criu with LXD it would greatly simplify this part of the code and improve the maintainability.

@checkpoint-restore/go-criu-maintainers What do you think?
